name: hive_generator
description: Extension for Hive. Automatically generates TypeAdapters to store any class.
version: 0.8.2
homepage: https://github.com/hivedb/hive/tree/master/hive_generator
documentation: https://docs.hivedb.dev/

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  analyzer: ">=0.36.0 <2.0.0"
  build: ^1.1.6
  dartx: ">=0.2.0 <1.0.0"
  fast_immutable_collections: 1.1.0
  hive: 
    path: ../hive
  source_gen: ">=0.9.4+4 <2.0.0"

dev_dependencies:
  build_runner: any
  build_test: any
  pedantic: "1.7.0"
  test: ^1.6.4
