name: hive
description: Lightweight and blazing fast key-value database written in pure Dart. Strongly encrypted using AES-256.
version: 1.5.0-pre
homepage: https://github.com/hivedb/hive/tree/master/hive
documentation: https://docs.hivedb.dev/

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  crypto: ">=2.1.0 <3.0.0"
  fast_immutable_collections: 1.1.0
  meta: ^1.1.7

dev_dependencies:
  dartx: ">=0.2.0 <1.0.0"
  mockito: ^4.1.1
  path: ^1.6.4
  pedantic: ^1.9.0
  pointycastle: ^1.0.2
  test: ^1.9.4